### ISSUE TITLE
Include Hide-WUUpdate.ps1?

### ISSUE THREAD

**Issue by creopard** [simdol/Remove-MS-Telemetry-and-Annoyances#2]
Hi,
this is by far the most complete colletion of removal options I found so far! :+1: 

Since you only seem to equire the script "Hide-WUUpdate.ps1" from the complete "Windows Update PowerShell Module" (PSWindowsUpdate.zip), why not include this file here directly?
This way it is not required to download "unzip.exe" and "PSWindowsUpdate.zip" from dropbox during the execution of the "remove_MS_telemetry.cmd" script, i.e. you would not require an active internet connection.

**Comment by WistfulAdris** [comment]
Thanks for your compliment. This script has not been originally written by me, and is merely continued support as the author discontinued.

As for the Powershell suggestion, if I am not mistaken, I am not allowed to redistribute the Powershell component. Thus, by including this on the script, I may be breaching the MS ToS. The another reason is that, the script aims to be in one file, and adding more files to the script will compromise the versatility. 

Thank you for your contribution!
