### ISSUE TITLE
Remove annoyance KB3086255 - disabled SafeDisc driver

### ISSUE THREAD

**Issue by creopard** [simdol/Remove-MS-Telemetry-and-Annoyances#3]
KB3086255 diables the SafeDisc copy protection service from MacroMedia that is required by older pc games.
This would affect most of the games listed here: http://www.gameburnworld.com/protectedgameslist.shtml
Uninstalling KB3086255 is not really necessary, as you can enable this service again manually either via "sc" or a registry entry, see
https://support.microsoft.com/en-us/kb/3086255

This could e.g. be achieved by adding another switch parameter by your script.

**Comment by WistfulAdris** [comment]
According to the KB by MS, it states that the service can be reactivated after the install of the update. Please correct me if I am wrong, thus as the update addresses security issue, unless it removes the functionality, I am not willing to add this to removal list.

Source: https://support.microsoft.com/en-us/kb/3086255
Under "Known issues in this security update"
