### ISSUE TITLE
Download additional tools from Github instead of Dropbox

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [simdol/Remove-MS-Telemetry-and-Annoyances#4]
Unzip tool and Powershell script could be added to GH's repo and downloaded from there. Moreover, PowerShell is likely able to unzip a file without external tools.

**Comment by creopard** [comment]
You could use a URL like https://raw.githubusercontent.com/simdol/Remove-MS-Telemetry-and-Annoyances/master/README.md in your script instead.
